### ISSUE TITLE
form withに変更できない

### ISSUE THREAD

**Issue by seina25** [webcamp-pro-HardMode/dwc-nagano-cake#19]
管理者ログインフォームがform forになっておりform withに変更しようと思いましたがやり方がわからず現状form forで実装しています。
model:@user←ここの変数でadminとかcurrent_adminにするとname errorが起きる。

（機能的には問題ないのですが、気になったので一応共有させてくださいませ。）

**Comment by kameoman** [comment]
記述方法が変わるみたいですね、必要箇所を教えてもらいたいです。
