### ISSUE TITLE
エンドユーザのログイン保持機能必要？

### ISSUE THREAD

**Issue by seina25** [webcamp-pro-HardMode/dwc-nagano-cake#20]
顧客のsign_inページでログイン状態を維持するRemember meチェックボックスがデフォルトで装備されているのですが、表示を消すか消さないかで迷っております。

Remember meチェックボックスについて
チェックを入れてログインをすると、remember_created_at機能に時間が入る。チェックを入れずにログインしたり、ログアウトしたりすると、remember_created_at機能はnilになる

２週間（時間の変更可能）ログイン状態が保持される機能
＝ブラウザを閉じて再度サイトに訪れてもログインされたままにする機能でやんす。

一応、この機能を使って顧客のログイン頻度を知ることもできるらしいので管理者側からしたら便利だけど、顧客側のログイン画面はごちゃごちゃせず、シンプルがいいのかな？
意見求む。

**Comment by kameoman** [comment]
内容を確認して返答します！
